server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          # Automatically create routes for services registered in Eureka based on their service IDs
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/videos/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
